### PR TITLE
Updated QGIS section

### PR DESCRIPTION
**Pull request by AndrewM-**
Removed information for obsolete QGIS version 2.  Revised information for QGIS 3.

### CODE REVIEW

**Comment by moovida** [comment]
Thanks @AndrewM- !
@brentfraser , can you look at this? I don't use QGIS and you wrote this section I think.

**Comment by brentfraser** [comment]
While I didn't write the old section (maybe I did a few edits?), I'm a casual user of QGIS so I'm happy to review this pull request.

**Comment by AndrewM-** [comment]
I wrote the old QGIS section, but thanks for reviewing it.  IO Geopaparazzi is available via pluggin manager for QGIS 3.10 but not 3.8.  I could add to the text that IO Geopaparazzi is not available for all versions of QGIS.

**Comment by brentfraser** [comment]
Hmm.  I installed QGIS 3.10 but Plugin Manager did not list the plug in.  I had to install it manually.  At any rate I guess it is a plugin/QGIS responsibility.

**Comment by AndrewM-** [comment]
Thanks for that.  The pluggin is flagged as experimental and in the pluggin manager, a check box on the settings page has to be checked to show the IO Geopaparazzi pluggin.  One thing that the pluggin does offer is a smooth way to create GIS layers for each form in a gpap file.  I have just tried it and created a memory layer with the results.  In the memory layer, I could delete the empty fields and then save as a shapefile or gpkg.  Quite a nice workflow.

**Pull request merged**
