### PR TITLE
some clarification

### PR DESCRIPTION
**Pull request by isync**
At least for me, these changes help to understand how Geopaparazzi uses map backends

### CODE REVIEW

**Comment by moovida** [comment]
Thanks for this. I am abroad for two weeks without decent connection. As soon as I am back, I will look into it and merge it in. Thanks

**Comment by isync** [comment]
Since I opened this pull request, I've found that docs are now in the wiki. I've edited the section there to reflect what's in here. So feel free to merge this pull request (if you want to have different docs in parallel for a while) or just discard it.

**Comment by moovida** [comment]
Hi @isync , I am not sure I understand. This pull request is in the usermanual which is visible at: geopaparazzi.eu

The wiki will be removed once this new manual is finished.

**Comment by isync** [comment]
> Hi @isync , I am not sure I understand. This pull request is in the usermanual which is visible at: geopaparazzi.eu

Ah! I see. From a comment (https://github.com/geopaparazzi/geopaparazzi/issues/289#issuecomment-140634857) I got the impression it was the other way round: that the wiki is now the main docs, while usermanual is the older/abandoned version. Anyway, thanks for merging in.

**Pull request merged**
